SkiSlopes/API/Models/ErrorViewModel.cs
namespace API.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SkiSlopes/API/Models/SkiSlopeRequest.cs
using Common.Enums;

namespace API.Models;

public record SkiSlopeRequest(string Place, int Number, string Name, SkiSlopeCondition Condition, string Details);

SkiSlopes/API/Controllers/HistoryController.cs
using Common.Constants;
using Common.Interfaces;
using Common.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.ServiceFabric.Services.Client;
using Microsoft.ServiceFabric.Services.Remoting.Client;
using System.Fabric;

namespace API.Controllers;

public class HistoryController : Controller
{
    public async Task<IActionResult> Index()
    {
        List<SkiSlopeState> skiSlopeStates = new();

        ITableStorage proxy = ServiceProxy.Create<ITableStorage>(new Uri(ServiceFabricConstants.TableStorage));
        List<SkiSlopeState> slopes = await proxy.GetAllSkiSlopeStates();
        skiSlopeStates.AddRange(slopes);

        ViewBag.SkiSlopes = skiSlopeStates;
        return View();
    }
}

SkiSlopes/API/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace API.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

SkiSlopes/API/Controllers/SkiSlopeStateController.cs
using API.Models;
using Common.Constants;
using Common.Helpers;
using Common.Interfaces;
using Common.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.ServiceFabric.Services.Client;
using Microsoft.ServiceFabric.Services.Remoting.Client;
using System.Fabric;

namespace API.Controllers;

public class SkiSlopeStateController : Controller
{
    public async Task<IActionResult> Index()
    {
        List<SkiSlopeState> skiSlopeStates = new();

        FabricClient fabricClient = new();
        int partitionsNumber = (await fabricClient
            .QueryManager
            .GetPartitionListAsync(new Uri(ServiceFabricConstants.Persister))).Count;
        int index = 0;

        for (int i = 0; i < partitionsNumber; i++, index++)
        {
            IPersister proxy = ServiceProxy.Create<IPersister>(
                new Uri(ServiceFabricConstants.Persister),
                new ServicePartitionKey(index % partitionsNumber));

            var slopes = await proxy.GetAllSkiSlopeStatesAsync();

            skiSlopeStates.AddRange(slopes);
        }

        ViewBag.SkiSlopes = skiSlopeStates;
        return View();
    }

    [HttpPost("SkiSlopeState/Add")]
    public async Task<IActionResult> AddSkiSlopeStateAsync(SkiSlopeRequest request, CancellationToken cancellationToken)
    {
        int partitionsNumber = await ProxyHelper.GetPartitionsNumberByUri(ServiceFabricConstants.Persister);
        int index = 0;

        for (int i = 0; i < partitionsNumber; i++, index++)
        {
            IPersister proxy = ServiceProxy.Create<IPersister>(
                new Uri(ServiceFabricConstants.Persister), 
                new ServicePartitionKey(index % partitionsNumber));

            await proxy.AddSkiSlopeStateAsync(new SkiSlopeState(
                place:      request.Place, 
                date:       DateTime.UtcNow, 
                number:     request.Number, 
                name:       request.Name, 
                condition:  request.Condition, 
                details:    request.Details));
        }

        return RedirectToAction("Index");
    }
}

SkiSlopes/API/Views/History/Index.cshtml
@using Common.Models;
<style>
    body {
        background-image: url("https://img.freepik.com/free-photo/travel-concept-with-landmarks_23-2149153256.jpg?w=2000");
        background-size: auto;
    }

    table {
        background-color: snow;
        margin-left: auto;
        margin-right: auto;
        border-style: solid;
        width: 50%;
    }

    h1 {
        font-family: 'Maiandra GD';
        color: snow;
        text-align: center;
        vertical-align: middle;
        font-size: 50px;
    }

    td, tr {
        font-family: 'Maiandra GD';
        font-size: 24px;
        text-align: center;
        vertical-align: middle;
    }

    h3 {
        font-family: 'Maiandra GD';
        font-size: 30px;
        text-align: center;
        vertical-align: middle;
        color: #ff1a1a;
    }

    input {
        height: 30px;
        text-align: center;
        vertical-align: middle;
        font-family: 'Times New Roman';
        font-size: medium;
    }

        input.check {
            margin-left: auto;
            margin-right: auto;
        }

    a {
        color: #1cc49d;
    }

        a.option {
            font-size: 140%;
            padding: 3px;
            background-color: black;
            margin: 4px;
        }

    input[type=radio] {
        border: 0px;
        width: 15%;
        height: 2em;
    }

    input.submit {
        color: #1cc49d;
        background-color: #1b2f31;
        border-radius: 50px;
        justify-content: center;
        align-items: center;
        height: 3em;
        width: 8em;
        font-size: large;
        font-weight: 600;
        margin-left: auto;
        margin-right: auto;
    }


    div.grid-container {
        background-color: snow;
        display: grid;
        padding: 10px;
        border-style: solid;
        margin: 10px;
        width: auto;
        margin-left: auto;
        margin-right: auto;
    }

    div.grid-item {
        font-family: 'Maiandra GD';
        font-size: 30px;
        text-align: center;
        display: inline-grid;
        background-color: cornflowerblue;
        border-style: solid;
        margin: 1px;
    }

</style>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="grid-container">
    @{
        <div class="grid-item" style="grid-column:1; grid-row:1">
            Place
        </div>
        <div class="grid-item" style="grid-column:2; grid-row:1">
            Date
        </div>
        <div class="grid-item" style="grid-column:3; grid-row:1">
            Number
        </div>
        <div class="grid-item" style="grid-column:4; grid-row:1">
            Name
        </div>
        <div class="grid-item" style="grid-column:5; grid-row:1">
            Condition
        </div>
        <div class="grid-item" style="grid-column:6; grid-row:1">
            Details
        </div>
        <div class="grid-item" style="grid-column:7; grid-row:1">
            Temperature
        </div>
        <div class="grid-item" style="grid-column:8; grid-row:1">
            WindSpeed
        </div>
        <div class="grid-item" style="grid-column:9; grid-row:1">
            Clouds
        </div>
        int r = 10;

        foreach (SkiSlopeState skiSlope in ViewBag.SkiSlopes)
        {
            <div class="grid-item" style="grid-column:1; grid-row:@r">
                @skiSlope.Place
            </div>
            <div class="grid-item" style="grid-column:2; grid-row:@r">
                @skiSlope.Date
            </div>
            <div class="grid-item" style="grid-column:3; grid-row:@r">
                @skiSlope.Number
            </div>
            <div class="grid-item" style="grid-column:4; grid-row:@r">
                @skiSlope.Name
            </div>
            <div class="grid-item" style="grid-column:5; grid-row:@r">
                @skiSlope.Condition
            </div>
            <div class="grid-item" style="grid-column:6; grid-row:@r">
                @skiSlope.Details
            </div>
            <div class="grid-item" style="grid-column:7; grid-row:@r">
                @skiSlope.Weather.Temperature
            </div>
            <div class="grid-item" style="grid-column:8; grid-row:@r">
                @skiSlope.Weather.WindSpeed
            </div>
            <div class="grid-item" style="grid-column:9; grid-row:@r">
                @skiSlope.Weather.Clouds
            </div>
            r++;
        }
    }


</div>

SkiSlopes/API/Views/Home/Index.cshtml
<style>
    body {
        background-image: url("https://img.freepik.com/free-photo/travel-concept-with-landmarks_23-2149153256.jpg?w=2000");
        background-size: auto;
    }

    table {
        background-color: snow;
        margin-left: auto;
        margin-right: auto;
        border-style: solid;
        width: 50%;
    }

    h1 {
        font-family: 'Maiandra GD';
        color: snow;
        text-align: center;
        vertical-align: middle;
        font-size: 50px;
    }

    td, tr {
        font-family: 'Maiandra GD';
        font-size: 24px;
        text-align: center;
        vertical-align: middle;
    }

    h3 {
        font-family: 'Maiandra GD';
        font-size: 30px;
        text-align: center;
        vertical-align: middle;
        color: #ff1a1a;
    }

    input {
        height: 30px;
        text-align: center;
        vertical-align: middle;
        font-family: 'Times New Roman';
        font-size: medium;
    }

        input.check {
            margin-left: auto;
            margin-right: auto;
        }

    a {
        color: #1cc49d;
    }

        a.option {
            font-size: 140%;
            padding: 3px;
            background-color: black;
            margin: 4px;
        }

    input[type=radio] {
        border: 0px;
        width: 15%;
        height: 2em;
    }

    input.submit {
        color: #1cc49d;
        background-color: #1b2f31;
        border-radius: 50px;
        justify-content: center;
        align-items: center;
        height: 3em;
        width: 8em;
        font-size: large;
        font-weight: 600;
        margin-left: auto;
        margin-right: auto;
    }


    div.grid-container {
        background-color: snow;
        display: grid;
        padding: 10px;
        border-style: solid;
        margin: 10px;
        width: auto;
        margin-left: auto;
        margin-right: auto;
    }

    div.grid-item {
        font-family: 'Maiandra GD';
        font-size: 30px;
        text-align: center;
        display: inline-grid;
        background-color: cornflowerblue;
        border-style: solid;
        margin: 1px;
    }

</style>

@{
    ViewData["Title"] = "Home Page";
}

<h1>Add ski slope state</h1>
<h3>@ViewData["Error"] </h3>


<form action="~/SkiSlopeState/Add" method="post">
    <div class="grid-container" style="width: 50%">
        <div class="grid-item" style="grid-column:1; grid-row:1">
            Place
            <input required type="text" name="Place" />
        </div>
        <div class="grid-item" style="grid-column:1; grid-row:2">
            Slope number:
            <input required type="number" name="Number" />
        </div>
        <div class="grid-item" style="grid-column:1; grid-row:3">
            Name:
            <input required type="text" name="Name" />
        </div>
        <div class="grid-item" style="grid-column:1; grid-row:4">
            Condition:
            <input type="radio" name="Condition" value="1" />
            <input type="radio" name="Condition" value="2" />
            <input type="radio" name="Condition" value="3" />
        </div>
        <div class="grid-item" style="grid-column:1; grid-row:5">
            Details:
            <input required type="text" name="Details" />
        </div>

        <div class="grid-item" style="grid-column:1; grid-row:6; background-color:white">
            <input required type="submit" class="submit" value="Submit" />
        </div>
    </div>
</form>

SkiSlopes/API/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - API</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/API.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">API</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SkiSlopeState" asp-action="Index">Ski slopes states</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="History" asp-action="Index">Ski slopes states history</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - API - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SkiSlopes/API/Views/SkiSlopeState/Index.cshtml
@using Common.Models;
<style>
    body {
        background-image: url("https://img.freepik.com/free-photo/travel-concept-with-landmarks_23-2149153256.jpg?w=2000");
        background-size: auto;
    }

    table {
        background-color: snow;
        margin-left: auto;
        margin-right: auto;
        border-style: solid;
        width: 50%;
    }

    h1 {
        font-family: 'Maiandra GD';
        color: snow;
        text-align: center;
        vertical-align: middle;
        font-size: 50px;
    }

    td, tr {
        font-family: 'Maiandra GD';
        font-size: 24px;
        text-align: center;
        vertical-align: middle;
    }

    h3 {
        font-family: 'Maiandra GD';
        font-size: 30px;
        text-align: center;
        vertical-align: middle;
        color: #ff1a1a;
    }

    input {
        height: 30px;
        text-align: center;
        vertical-align: middle;
        font-family: 'Times New Roman';
        font-size: medium;
    }

        input.check {
            margin-left: auto;
            margin-right: auto;
        }

    a {
        color: #1cc49d;
    }

        a.option {
            font-size: 140%;
            padding: 3px;
            background-color: black;
            margin: 4px;
        }

    input[type=radio] {
        border: 0px;
        width: 15%;
        height: 2em;
    }

    input.submit {
        color: #1cc49d;
        background-color: #1b2f31;
        border-radius: 50px;
        justify-content: center;
        align-items: center;
        height: 3em;
        width: 8em;
        font-size: large;
        font-weight: 600;
        margin-left: auto;
        margin-right: auto;
    }


    div.grid-container {
        background-color: snow;
        display: grid;
        padding: 10px;
        border-style: solid;
        margin: 10px;
        width: auto;
        margin-left: auto;
        margin-right: auto;
    }

    div.grid-item {
        font-family: 'Maiandra GD';
        font-size: 30px;
        text-align: center;
        display: inline-grid;
        background-color: cornflowerblue;
        border-style: solid;
        margin: 1px;
    }

</style>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="grid-container">
    @{
        <div class="grid-item" style="grid-column:1; grid-row:1">
            Place
        </div>
        <div class="grid-item" style="grid-column:2; grid-row:1">
            Date
        </div>
        <div class="grid-item" style="grid-column:3; grid-row:1">
            Number
        </div>
        <div class="grid-item" style="grid-column:4; grid-row:1">
            Name
        </div>
        <div class="grid-item" style="grid-column:5; grid-row:1">
            Condition
        </div>
        <div class="grid-item" style="grid-column:6; grid-row:1">
            Details
        </div>
        <div class="grid-item" style="grid-column:7; grid-row:1">
            Temperature
        </div>
        <div class="grid-item" style="grid-column:8; grid-row:1">
            WindSpeed
        </div>
        <div class="grid-item" style="grid-column:9; grid-row:1">
            Clouds
        </div>
        int r = 10;

        foreach (SkiSlopeState skiSlope in ViewBag.SkiSlopes)
        {
            <div class="grid-item" style="grid-column:1; grid-row:@r">
                @skiSlope.Place
            </div>
            <div class="grid-item" style="grid-column:2; grid-row:@r">
                @skiSlope.Date
            </div>
            <div class="grid-item" style="grid-column:3; grid-row:@r">
                @skiSlope.Number
            </div>
            <div class="grid-item" style="grid-column:4; grid-row:@r">
                @skiSlope.Name
            </div>
            <div class="grid-item" style="grid-column:5; grid-row:@r">
                @skiSlope.Condition
            </div>
            <div class="grid-item" style="grid-column:6; grid-row:@r">
                @skiSlope.Details
            </div>
            <div class="grid-item" style="grid-column:7; grid-row:@r">
                @skiSlope.Weather.Temperature
            </div>
            <div class="grid-item" style="grid-column:8; grid-row:@r">
                @skiSlope.Weather.WindSpeed
            </div>
            <div class="grid-item" style="grid-column:9; grid-row:@r">
                @skiSlope.Weather.Clouds
            </div>
            r++;
        }
    }


</div>